### ISSUE TITLE
Remote read

### ISSUE THREAD

**Issue by stuart-c** [dpattmann/prometheus-timestream-adapter#1]
While you are correct in saying that Timestream has a Grafana plugin to allow you to create dashboards it would still be useful to be able to read the data back into Prometheus.

An example would be to allow for alerts via Prometheus and Terraform.

With Timestream only available for remote write these is no way to have alerts that query data older than the local Prometheus retention time, even if Timestream has the data.

Is this something you might consider adding?

Thanks

**Comment by dpattmann** [comment]
Yes, but I will need some time to implement this.
