### ISSUE TITLE
expanded README?

### ISSUE THREAD

**Issue by htsoi-boto** [dpattmann/prometheus-timestream-adapter#2]
Would like to know a bit more on how to get this running? from the main.go I only see variables for us-east-1 but no AWS account id or credentials, how does it know to forward to timestream?

The documentation is a bit lacking, is there anyway to get this working? Was successful in building docker image and also via go and running it listening on 9201. Created prometheus db and table in timestream but no data shows up.

**Comment by dpattmann** [comment]
Hi @htsoi-boto, you can use environment variables, a ~/.aws/credentials file or an IAM Role/Policy to access your timestream database.

**Comment by htsoi-boto** [comment]
Awesome, will try it out. Thanks!
